version: '3'
services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - backend
  backend:
    image: book-management-system-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
